### ISSUE TITLE
Latency Threshold in the example graphs

### ISSUE THREAD

**Issue by elishafer** [2b-t/docker-realtime#7] opened 2023-05-23 07:20 UTC
In the [Example section](https://github.com/2b-t/docker-realtime#2-example) you have two graphs. One with docker and one without.
It seems that the test without docker has a higher latency threshold than the one with docker.
Do you perhaps know the reason why this happens? I would think that a system with docker would have a higher latency threshold.

**Comment by 2b-t** [comment] 2023-05-23 20:49
Hi @elishafer,
I do not see a noticeable difference between the two graphs. The data was obtained by 5 minutes of benchmark and I would assume that any visible difference would be caused by the **small sample size** (normally you would run these tests for several hours/days) as well as **background load**. As Docker is based on abstractions on the Linux kernel level , it should achieve native performance on a Linux machine. After all a Docker container still uses the same kernel as the host system! The only aspects that might suffer a slight performance hit are those where some form of virtualization is involved, such as I/O and networking. Latter can be worked around by removing the isolation between the container's network stack and the host systems with [`net=host`](https://docs.docker.com/network/host/). For actual benchmarks you might have a look at [this fairly old research paper from IBM](https://ieeexplore.ieee.org/document/7095802) (also [available for free on IBM Research](
https://dominoweb.draco.res.ibm.com/reports/rc25482.pdf)).

**Comment by elishafer** [comment] 2023-05-24 08:27
Thanks for the quick and detailed response! Also thank you for your guides, your [motivation section for academy](https://github.com/2b-t/docker-for-ros/blob/main/doc/Motivation.md#3-why-is-docker-important-in-particular-for-academic-and-research-institutions) really struck a chord with me.

**Comment by 2b-t** [comment] 2023-05-24 18:02
Glad to hear that!
Let me know if we can close this issue.

**Closed as completed** 2023-05-24 18:39 UTC
